import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Printer, Download } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';

interface PrintableReportProps {
  title: string;
  subtitle?: string;
  asOfDate?: string;
  children: React.ReactNode;
  showPrintButton?: boolean;
  showExportButton?: boolean;
  onExport?: () => void;
  landscape?: boolean;
}

export default function PrintableReport({
  title,
  subtitle,
  asOfDate,
  children,
  showPrintButton = true,
  showExportButton = true,
  onExport,
  landscape = false,
}: PrintableReportProps) {
  const { currentCompany } = useAuth();
  const contentRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });
  };

  return (
    <div className={landscape ? 'print-landscape' : ''}>
      {/* Print Header - only visible when printing */}
      <div className="print-header hidden print:block">
        <h1>{currentCompany?.name || 'Company Name'}</h1>
        {currentCompany?.gstin && <p>GSTIN: {currentCompany.gstin}</p>}
        <h2>{title}</h2>
        {subtitle && <p>{subtitle}</p>}
        {asOfDate && <p>As of {formatDate(asOfDate)}</p>}
      </div>

      {/* Action Buttons - hidden when printing */}
      <div className="no-print flex items-center gap-2 mb-4">
        {showPrintButton && (
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>
        )}
        {showExportButton && onExport && (
          <Button variant="outline" size="sm" onClick={onExport}>
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>
        )}
      </div>

      {/* Report Content */}
      <div ref={contentRef} className="print-content">
        {children}
      </div>

      {/* Print Footer - only visible when printing */}
      <div className="print-footer hidden print:block">
        <p>
          Generated by Zara Books on {new Date().toLocaleDateString('en-IN')} at{' '}
          {new Date().toLocaleTimeString('en-IN')}
        </p>
      </div>
    </div>
  );
}

// Component to format currency amounts in reports
export function ReportAmount({
  value,
  showCurrency = true,
  className = '',
}: {
  value: number;
  showCurrency?: boolean;
  className?: string;
}) {
  const isNegative = value < 0;
  const formattedValue = new Intl.NumberFormat('en-IN', {
    style: showCurrency ? 'currency' : 'decimal',
    currency: 'INR',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(Math.abs(value));

  return (
    <span
      className={`financial-amount ${isNegative ? 'financial-negative' : ''} ${className}`}
    >
      {isNegative ? `(${formattedValue})` : formattedValue}
    </span>
  );
}

// Table row styling for financial statements
export function FinancialRow({
  label,
  value,
  previousValue,
  indent = 0,
  isTotal = false,
  isSubtotal = false,
  isBold = false,
  className = '',
}: {
  label: string;
  value: number;
  previousValue?: number;
  indent?: number;
  isTotal?: boolean;
  isSubtotal?: boolean;
  isBold?: boolean;
  className?: string;
}) {
  const rowClass = `
    ${isTotal ? 'financial-row-total' : ''}
    ${isSubtotal ? 'financial-row-subtotal' : ''}
    ${isBold ? 'font-semibold' : ''}
    print-avoid-break
    ${className}
  `;

  return (
    <tr className={rowClass}>
      <td style={{ paddingLeft: `${indent * 1.5}rem` }}>{label}</td>
      <td className="text-right">
        <ReportAmount value={value} />
      </td>
      {previousValue !== undefined && (
        <td className="text-right">
          <ReportAmount value={previousValue} />
        </td>
      )}
    </tr>
  );
}

// Section header for financial statements
export function ReportSection({
  title,
  children,
  className = '',
}: {
  title: string;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={`print-avoid-break ${className}`}>
      <h3 className="text-lg font-semibold mt-6 mb-3 border-b pb-2">{title}</h3>
      {children}
    </div>
  );
}
